# Generated by Django 2.2.5 on 2020-12-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('brand', models.CharField(max_length=80, verbose_name='Marca')),
                ('model', models.CharField(max_length=80, verbose_name='Modelo')),
                ('serial', models.CharField(max_length=100, verbose_name='Serial')),
                ('type_pro', models.CharField(max_length=100, verbose_name='Tipo')),
                ('date_purchase', models.DateField(verbose_name='Fecha de compra')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('state', models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'Zona de Campo',
            },
        ),
    ]
