# Generated by Django 3.1.2 on 2020-12-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201210_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_purchase',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de compra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_pro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo'),
        ),
    ]
