# Generated by Django 3.1.2 on 2020-12-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_purchase',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha de compra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad'),
        ),
    ]
