# Generated by Django 3.1.2 on 2020-11-26 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0002_schedule_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('file', models.FileField(upload_to='')),
                ('name_operator', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_zona', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_labor', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='schedules.schedule', verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Bitácora',
            },
        ),
    ]
