# Generated by Django 3.1.2 on 2020-12-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='worklog',
            name='lng',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
