# Generated by Django 3.1.2 on 2020-12-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0002_auto_20201209_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
