# Generated by Django 3.1.2 on 2020-12-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0003_worklog_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Audio'),
        ),
    ]
