# Generated by Django 3.1.2 on 2020-12-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklogs', '0004_auto_20201210_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
