# Generated by Django 3.1.2 on 2020-11-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.CharField(default=0, max_length=50, verbose_name='Cedula'),
            preserve_default=False,
        ),
    ]
