# Generated by Django 3.1.2 on 2020-11-24 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_auth_provider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
