# Generated by Django 3.1.2 on 2020-11-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tamaño'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de suelo'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
    ]
