# Generated by Django 3.1.2 on 2020-11-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_zone_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='zone',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
