# Generated by Django 3.1.2 on 2020-11-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_auto_20201104_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Zona de Campo'},
        ),
    ]
