# Generated by Django 3.1.2 on 2020-11-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0003_auto_20201119_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='location',
        ),
        migrations.AddField(
            model_name='zone',
            name='lat',
            field=models.TextField(default=0, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='lng',
            field=models.TextField(default=0, verbose_name='Longitud'),
            preserve_default=False,
        ),
    ]
