# Generated by Django 3.1.2 on 2020-11-17 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labors', '__first__'),
        ('zones', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('schedule_date', models.DateField(verbose_name='Fecha')),
                ('start_hour', models.TimeField(blank=True, null=True, verbose_name='Hora inicial')),
                ('final_hour', models.TimeField(blank=True, null=True, verbose_name='Hora final')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labors.labor', verbose_name='Labor de Campo')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operario')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zones.zone', verbose_name='Zona de Campo')),
            ],
            options={
                'verbose_name': 'Programacion',
            },
        ),
    ]
