# Generated by Django 3.1.2 on 2020-11-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='name_operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
